### ISSUE TITLE
Latest update breaking Obsidian, removes Obsidian Folder/File Explorer

### ISSUE THREAD

**Issue by ccjcan** [RafaelGB/obsidian-db-folder#178]
As soon as I create a new database folder the plugin replaces the file explorer (now gone) and I can't get it back.
I only have dataview, templater and dbfolder plugins installed, fresh vault.

**To Reproduce**
If applicable, add your configuration YAML of your database to reproduce the bug

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by RafaelGB** [comment]
Hi @ccjcan , sorry for the inconvenience.

This was fixed with https://github.com/RafaelGB/obsidian-db-folder/issues/172 , next week I will launch a version including that change

Its an incompatibility with the actual Insider version of Obsidian where core things were changed

Closed as a duplicate

**Comment by RafaelGB** [comment]
If you close and start again the app you can get your file explorer back

**Comment by arminta7** [comment]
You can also drag the db page into the main window and use the command palette to open the file explorer again.
