### ISSUE TITLE
Nested Metadata

### ISSUE THREAD

**Issue by kvietcong** [RafaelGB/obsidian-db-folder#194]
**Is your feature request related to a problem? Please describe.**
It seems that the plugin doesn't handle nested metadata at all. I tried making changes but it severely mangled my current metadata and reformatted it in a breaking way.

Metadata beforehand:

![image](https://user-images.githubusercontent.com/32186663/177441778-a469f037-fe37-466f-942e-5e88aaf9b716.png)

Example Column: (I put in a test value after this)
![image](https://user-images.githubusercontent.com/32186663/177441865-ef047adf-9821-4196-ad42-3f8b4cfb00d5.png)

Metadata afterward:
![image](https://user-images.githubusercontent.com/32186663/177441983-0ca90bbb-0a0d-45de-8808-6fc42f6d5cbe.png)

**Describe the solution you'd like**
Would it be possible to handle nested metadata without major reformatting and would it be possible to edit nested meta data fields through accessors like `this.very.nested.field` or in my case `content.my.rating`

**Describe alternatives you've considered**
N/A

**Comment by RafaelGB** [comment]
sure!, will be considered

**Comment by dalewking** [comment]
Here is what I want to use this for: https://jeffszuc.com/tutorial/how-to-add-habit-tracking-to-obsidian-with-java-script-and-dataview.

Nesting the variables makes it much easier to filter them

**Comment by RafaelGB** [comment]
This issue will be a nice improvement for the edit engine, but requires a big effort. We need to construct an unmarshall function from yaml to string

I will work on it as soon as the mobile version was fixed

**Comment by RafaelGB** [comment]
Mybad to do not use this native function of Obsidian!
```ts
import { stringifyYaml } from "obsidian";
```

Nested metadata will be supported with the next version

**Comment by www-wagner** [comment]
I've tried the version that implemented this issue and I can't understand what was really done.

The 2.6.7 release section says "Frontmatter editions now respect nested metadata". This means that nested metadata **won't be messed up** by the plugin or nested metadata will be **supported** by the plugin?

Because I thought the @kvietcong possible solution was accepted and implemented, where:
```yaml
level1:
  level2:
```
would be considered as `level1.level2` as the name field by the plugin.

When I create a field separating field levels by dot, the DB turns empty (error). ![image](https://user-images.githubusercontent.com/18124316/192816566-e19fb404-8614-48fc-b4c1-486abf182af8.png)

When I try to create a field that already exists in DB ![image](https://user-images.githubusercontent.com/18124316/192818378-1b490373-4d65-4dc1-aa85-57e819e5ab48.png), only the `level1` can be added ![image](https://user-images.githubusercontent.com/18124316/192818521-17f2a809-0ff5-4696-bfc7-01543125f1fe.png)
and the data is shown as json in DB: ![image](https://user-images.githubusercontent.com/18124316/192818819-0c440c98-12f7-43cd-bf7d-97d748e60eca.png).
If this data is edited by plugin, the nested metadata in YAML will be messed up:
![image](https://user-images.githubusercontent.com/18124316/192819086-7499eeef-e49e-4a6f-a3e6-a1beeb768cb1.png).

Is there another issue related to what I've described above?

**Comment by RafaelGB** [comment]
We have a missunderstanding here then. What we achieve now is to respect the nested properties when you edit a different one, since before it returned them as shown in your capture.

The possibility of being able to edit nested values is not yet contemplated. I can open an incident based on your comment to leave it contemplated in the future

**Comment by RafaelGB** [comment]
I will support your request here https://github.com/RafaelGB/obsidian-db-folder/issues/442
