### ISSUE TITLE
Items created in parent instead of within DB Folder

### ISSUE THREAD

**Issue by airways** [RafaelGB/obsidian-db-folder#261]
**Describe the bug**
The database folder seems to be creating items within its own parent rather than within itself.

**To Reproduce**
1. Add a db folder to existing folder
2. All notes in that folder appear in database folder table view
3. Create new rows
4. Observe they are in the parent

**Expected behavior**
Expect a new db folder in a parent folder with existing items to be empty.
Expect new items added to db folder to create them within the db folder.

**Screenshots**
<img src="https://user.fm/files/v2-4666c4be1798dda7b4cf1f478dc8b93a/dbfolder220814.png"/>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.1.2

**Comment by RafaelGB** [comment]
hi @airways , This is the expected behaviour. The database takes as reference its own folder and takes the info inside, its not a folder itself.

If you want another source you can select it in its settings section

<img width="954" alt="Screenshot 2022-08-15 at 10 59 50" src="https://user-images.githubusercontent.com/11924043/184607011-0c94b369-284d-4aa0-a241-24e719e5cc82.png">

**Comment by airways** [comment]
Ah okay I see. Would it be possible for this to have a mode where it really is a folder and shows the contents of itself? I guess the name got me, but that would be kind of great. Maybe I can do it with folder notes though...
