### ISSUE TITLE
[FR] Input for new columns inside the add column menu

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#267]
The process to create a new column in the new version is slower than in previous versions.
It would be interesting to add an input box so that from the new window you can create new columns.

The ideal would be:
-write the name of the new column in the box
-click on the add icon
-that the name of that column appears in the list below

It would be nice if the window didn't close and you could add several consecutively each time you press the icon.

![Nuevo proyecto](https://user-images.githubusercontent.com/7627504/185431470-f83a6476-30d0-405e-9a8f-1213d6450ecd.jpg)

**Comment by RafaelGB** [comment]
You can add new columns with the previous way on column menu.

About the idea of add an input with the new column will be the next version of this menu. Requires that the actual name does not exist previously.

About not closing the Manu after edit already happens with the "existing column" version. I want to show the added columns to the hidden options too, so that's why I close the menu for now

@javiavid  thanks for your ideas as always
