### ISSUE TITLE
[FR]: Colour selector for quick filters

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#492]
### Contact Details

danny@dannyhatcher.com

### Present your request

Putting a right-click menu in for the select and tag property types so that the background colour is easier to change.

Also adding an option to change the group filter colour shown at the top of the database view.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
to respect the principle of single responsiveness in the architecture of the application I think it is more maintainable to keep the color selection in the column menu since changing it requires rendering the entire table


About to change the quick filters could be cool and the selector its already done for the tags/select. I will consider it :)

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/206716285-84f3a2e5-c281-486e-8a1d-669d669403b5.mov

**Comment by DannyHatcher-Git** [comment]
I can't see this option in my database files, is it in settings somewhere?

**Comment by RafaelGB** [comment]
Its not available yet. Will be one of the next features 😊 Hope you can enjoying it soon. With the onboarding of Obsidian 1.1 I want to wait until the official release to take advantage of some API improvements

**Comment by DannyHatcher-Git** [comment]
ah that sounds good and exciting!
