### ISSUE TITLE
[FR] Relation/Lookup/Rollup column types

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#53]
Ability to do relations/lookups in a column. Dataview currently can do this with dot notation (`[[link]].field`). This is a powerful feature of Notion/Coda databases. 

Related is the ability to auto-populate the relation back to the original entity as shown in the Notion screenshot:

<img width="413" alt="Screen Shot 2022-05-17 at 13 06 05" src="https://user-images.githubusercontent.com/7927356/168870772-2ab982bc-c2c4-43a5-ac2a-39eec877e958.png">

**Comment by RafaelGB** [comment]
The goal of this plugin is to get that Feature! After 1 year of Obsidian I still miss it...

**Comment by crazymedguy** [comment]
That would be really legendary

**Comment by crazymedguy** [comment]
Was thinking - would be nice to have a Property type, kind of a Relation property, that lists all the [[backlinks]] linked outwards from the note.

**Comment by RafaelGB** [comment]
internally can be done with frontmatter fields too. Thanks for your comments @crazymedguy , this feature will arrive sooner or later :)

**Comment by DmitryKorzhov** [comment]
@RafaelGB hey! Thank you for your product! It's very useful! 

Could you tell approximately date of implementing this features? 

Dataview relations don't work correctly. And I don't remember solution who can make relation between tables. It's awesome and our team very want to use it!

**Comment by RafaelGB** [comment]
Hi @DmitryKorzhov , thanks for your support!

Once the base is stable, my intention is to bring this functionality during this year, early next.
This forecast can be reduced depending on the number of collaborations received

**Comment by RafaelGB** [comment]
I am starting with the most difficult feature until now. Relations

<img width="978" alt="Screenshot 2022-10-25 at 00 00 51" src="https://user-images.githubusercontent.com/11924043/197638369-da175300-3b14-4d08-b2d8-f363215905fb.png">

wish me luck, i'll need it =P

**Comment by GaboCapo** [comment]
An idea how I currently map relations via the DB Folder Plugin: I use the internal linking of Obsidian with two square brackets [[relation]] for the entry in the DB and its relation. Actually the feature of the plugin should only make sure that the relation in the header is recognized as such on the way back. This could also be implemented by copying this relation entry and pasting it below the header. However, one would have to consider how to delete the relation again. Possibly manually. That would not be bad. As long as a relation results in both sides. I try now also at a solution, since I find it important. 




![Image](https://user-images.githubusercontent.com/39612138/197653552-af8da138-5eab-42f8-979c-0669843cbf48.png)



![Image](https://user-images.githubusercontent.com/39612138/197653572-d47eedb9-4f4f-4ff8-bf7b-5c986e31dc65.png)

**Comment by RafaelGB** [comment]
The idea is to associate another ddbb to a column. When you select your relation cell, a list of (not filtered) files will be displayed.

https://user-images.githubusercontent.com/11924043/198278223-e3372df4-f06b-4a2c-9671-1786feca7f04.mov

The challenge now its to use the internal values inside the formulas. Natively are not included

**Comment by RafaelGB** [comment]
Commit 2a706160

2.8.0 is alive with the first version of the relations. Rollup functions will be added during the following versions
