### ISSUE TITLE
Support of Obsidian-Projects

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#574]
Support for https://github.com/marcusolsson/obsidian-projects/issues/27#issuecomment-1299166903

**Comment by RafaelGB** [comment]
Finally I found a way to mock the Obsidian architecture object `WorkspaceLeaf`

The Idea will be to create a File associated with the view

```typescript
if (this.isConfigEmpty(config)) {
            // If the config is empty, we need to create a Default 
            const leaf = app.workspace.getLeaf();
            const file = resolve_tfile("pruebas.md");
            this.view = new DatabaseView(leaf, this.plugin, file);
            this.view.initRootContainer(file);
            this.view.initDatabase().then(() => {
                LOGGER.debug("Database initialized successfully from project view");
                this.dataEl = contentEl.createDiv().appendChild(this.view.containerEl);
            });
        }
```

**Comment by cesarpereira904** [comment]
Amazing achievement Rafael, I really think these both plugins complement themself.
Can't wait to try it!

**Comment by RafaelGB** [comment]
First version working.

https://user-images.githubusercontent.com/11924043/201439767-940ac914-f0a7-4ac6-99fd-cb67f2ea6e36.mov

It will be available with next version and we will continue working on it with your feedback =)

**Comment by cesarpereira904** [comment]
Hi Rafael,

I was trying this integration with Projects and it works perfectly. I mean, it looks like native to the Projects plugin.



If you allow me I would only make one suggestion, which I'm not sure its possible.

As we create a Project we can define source data from either a folder or a Datavierw query:


![Image](https://user-images.githubusercontent.com/70922426/201484531-4f769d5e-b414-4304-be00-5322f95d080c.png)





I think it would be great if the Database Folder view would use the same Folder or Dataview Query as defined in the Project (same as defined above).


![Image](https://user-images.githubusercontent.com/70922426/201484571-8cb442b2-0ab1-4b60-afa9-e3edd80b3379.png)



The way I was imagining is that by default when a user creates a new Database Folder view inside Projects, that view data will be limited to the data defined for this specific project view (by either Dataview or by folder ):


![Image](https://user-images.githubusercontent.com/70922426/201484688-74ae7cd4-57f7-4702-a7fd-a7b668405098.png)


At this monentn:
- I create a new project in the Projects plugin using a Dataview query where I will only see the current week notes.
- I create a calendar view and a board view in the Projects plugin (where I will see only current week notes)
- I create a database folder view where in order to see the exactly same notes I see in the other views I need to open database folder settings and set same query as previously did for this project.

Desirable behaviour
- I create a new project in the Projects plugin using a Dataview query where I will only see current week numbers notes.
- I create a calendar view and a board view in the Projects plugin (where I will see only current week notes)
- I create a database folder view where I see the exactly same notes as seen in the other views.

what you think? Does makes sense what I'm suggesting ?

Maybe if it would be possible on the  database Folder view creation to pre-fill or predefine the source data as the same used in the project view. So if user still would like to change the source of the databased folder later he still would be able to do it.

**Comment by RafaelGB** [comment]
yeah I am agree there is window for improvement. Its the first iteration to just test if all works as it should.

The next steps:
- [ ] use same init configuration when the dbfolder file is created
- [ ] generate the same columns of the rest of the views (at start, the user should edit them without modify the rest of the views I think)
- [ ] hide the same columns (dbfolder already allow it too)
- [ ] update that info when projects plugin does

**Comment by RafaelGB** [comment]
we can open another issue for this tasks ;)

**Comment by cesarpereira904** [comment]
I see you have even more ambitious plans regarding this integration!

Great to hear!

As you go thru next steps I will let you know about any other ideas or suggestions. 

While so, if you need an opinion on some functionally feel free to ask!

Congrats!

**Comment by LeonardoGentile** [comment]
Hello, this is awesome, thanks!
Although it's not very clear how to make the two plugins work correctly and not cluttering the folders with extra files, could either of the two plugins owner expand a bit the documentation on this topic?

It's not clear:
- should I create a DB-folder file then projects? Or vice versa?
- A sub-folder view in Obsidian-Project seems to create a new DB-folder file, is that the expected behavior?  If so, shouldn't this be more of an export option instead of a view?
- why can't the two plugins be merged and give us the best of the two ? (That seems a bit ambitions and pushy 🤣)

Great work!
