### ISSUE TITLE
[FR]: Support DataviewJS as source of the database

### ISSUE THREAD

**Issue by yurijserrano** [RafaelGB/obsidian-db-folder#628]
### Contact Details

yurijserrano@gmail.com

### Present your request

Good Evening @RafaelGB 

I hope you are well

I noticed that the plugin supports DQL as source for the Database but not the DataviewJS as can be seen in the video on the link below:

**[DATAVIEWJS - NOT SUPPORTED](https://share.getcloudapp.com/eDunA6Kr)**

Therefore, I wonder if you could also include DataviewJS, so we can use it as the source of the Database as well.

I am waiting to hear from you

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Could be interesting. Added to the roadmap =)

**Comment by yurijserrano** [comment]
Thank you so @RafaelGB 

I do really appreciate.

If you need anything else, just let me know.

Have a wonderful day.

**Comment by RafaelGB** [comment]
I was investigating this feature but I can not see an official way to obtain this as source

https://blacksmithgu.github.io/obsidian-dataview/api/code-reference/

You can render the content but its not we are intended here

**Comment by yurijserrano** [comment]
First, Happy New Year @RafaelGB for you and your family :)

As you mentioned it would be possible to use dv.executeJs(source), so theoretically speaking we can use **dv.pages(source)** to get all the pages that are according to the source passed to us as you can see below:

![image](https://user-images.githubusercontent.com/14169134/210358022-6c977502-5804-49d8-854d-49a0bd4abd12.png)


So, in the DB configuration you could put an option that we stipulate the source that would bring all the pages that follow that criteria.


In case you want to extend it in the future, you could put an option that the user includes the headers in relation to the data brought by **dv.pages** and that would be rendered through **dv.table**, as you can see below:

![image](https://user-images.githubusercontent.com/14169134/210358503-1fbf4833-bd4f-4403-823f-9105422c7dc8.png)


If you need anything else just let me know.


Have a great day.

**Comment by RafaelGB** [comment]
Oh I see.

We are currently using dv.pages() for current folder, tags and filters

I understood you request a js criteria.

We can easily expose this kind of sources but without conditions like sort of where clauses

**Comment by yurijserrano** [comment]
Thank you so much @RafaelGB 

This could be a start, but at this situation I do not think the sort and where clauses will be necessary since we can filter the data and sort through the DB folder plugin itself.

If you need anything else just let me know.

Have a great day.

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/211631081-b429be3a-c68f-4e59-85e9-74842c427ebf.mov

**Comment by yurijserrano** [comment]
Good Afternoon @RafaelGB 

I hope you are well

Awesome, this feature will help a lot of users that rely on the DataviewJS.

Great job 👍 .

I will be waiting the new version with this feature.


Have a wonderful day :)

**Comment by zcysxy** [comment]
Hi @RafaelGB, thanks for this great feature! Is it possible to support general DataviewJS (with variable declaration, where clauses etc.)? Maybe use the `eval` function? I tried to modify the code but couldn't locate the correct parts..

**Comment by onoter** [comment]
Yeah I think it would be great to support full dataviewjs, instead of just the `pages` function we have right now. The filtering will be very flexible using the [where](https://blacksmithgu.github.io/obsidian-dataview/api/data-array/#raw-interface) function. And we'll be able to choose columns via `dv.table` as we can't do that by specifying source as Dataview query ([DQL](https://blacksmithgu.github.io/obsidian-dataview/queries/dql-js-inline/)), since we are not allowed to write the first line (`TABLE ...`) of the DQL as source of dbfolder. 

@zcysxy I think I found it
https://github.com/RafaelGB/obsidian-db-folder/blob/5388538a1f1b9b159c0728b4d7a6ad3e33a9da49/src/helpers/VaultManagement.ts#L128-L130

The `obtainPagesResult` function is essentially calling the [pages](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/api/plugin-api.ts#L153)  function of dataview api (`DataviewApi`).
https://github.com/RafaelGB/obsidian-db-folder/blob/5388538a1f1b9b159c0728b4d7a6ad3e33a9da49/src/helpers/VaultManagement.ts#L160-L162

As I was trying to figure out how dataview plugin was able to run code from text. I found this api function [DataviewApi.executeJs()](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/api/plugin-api.ts#L452) seems to do the job.  
Note that `executeJs` and the `pages` function I mentioned above are both dataview api functions. They both belong to `DataviewApi`. Since `pages` is already working, I believe `executeJs` probably works too. 

@RafaelGB has mentioned this function [above](https://github.com/RafaelGB/obsidian-db-folder/issues/628#issuecomment-1369214516), though I don't get what he meant. Did he mean he failed to run `executeJs` or couldn't find it? 

I did a quick test in a dataviewjs block:
````
```dataviewjs
dv.executeJs(`
dv.list(dv.pages().limit(1))
`)
```
````

and it worked just fine.

I think using executeJs will do. Have you tried?

I also did more digging as I was curious how dataview plugin achieved running code from text. Here is the summary. If I understand correctly, the code execution happens in the [renderer.load()](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/api/plugin-api.ts#L463) line in [executeJs definition](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/api/plugin-api.ts#L452). That `renderer` is a `DataviewJSRenderer` object. 

DataviewJSRenderer extends DataviewRefreshableRenderer

DataviewRefreshableRenderer extends MarkdownRenderChild

import { App, MarkdownRenderChild } from "obsidian";

We can find MarkdownRenderChild in [obsidian.d.ts](https://github.com/obsidianmd/obsidian-api/blob/583ba39e3f6c0546de5e5e8742256a60e2d78ebc/obsidian.d.ts#L2055): 
MarkdownRenderChild extends Component

And you can find the declaration of [Component.onload()](https://github.com/obsidianmd/obsidian-api/blob/583ba39e3f6c0546de5e5e8742256a60e2d78ebc/obsidian.d.ts#L644-L649): 
```typescript
/**
 * Override this to load your component
 * @public
 * @virtual
 */
onload(): void;
```

This onload function is overridden by [DataviewRefreshableRenderer.onLoad()](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/ui/refreshable-view.ts#L21) 

In this function, I believe the line [this.render()](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/ui/refreshable-view.ts#L22) is what does the job. However `DataviewRefreshableRenderer`'s [render function is abstract](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/ui/refreshable-view.ts#L19) : 
`abstract render(): Promise<void>;`

It is [overridden in DataviewJSRenderer](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/ui/views/js-view.ts#L13)
In this render function, `asyncEvalInContext` is what does the job:
```typescript
// Assume that the code is javascript, and try to eval it.
try {
    await asyncEvalInContext(
        DataviewJSRenderer.PREAMBLE + this.script,
        new DataviewInlineApi(this.api, this, this.container, this.origin)
    );
} catch (e) {
```

 Finally, [we can see](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/api/inline-api.ts#L419-L437) it's using an eval function: 
```typescript
/**
 * Evaluate a script where 'this' for the script is set to the given context. Allows you to define global variables.
 */
export function evalInContext(script: string, context: any): any {
    return function () {
        return eval(script);
    }.call(context);
}

/**
 * Evaluate a script possibly asynchronously, if the script contains `async/await` blocks.
 */
export async function asyncEvalInContext(script: string, context: any): Promise<any> {
    if (script.includes("await")) {
        return evalInContext("(async () => { " + script + " })()", context) as Promise<any>;
    } else {
        return Promise.resolve(evalInContext(script, context));
    }
}
```

**Comment by onoter** [comment]
@zcysxy great to hear from you so quick.

 We still have two plans. 
- Plan A: modify executeJs to let it return the value. (May require a FR in Dataview repo)
- Plan B: use the eval function just like what is done in the dataview plugin source code. 

[DataviewInlineApi.executeJs()](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/api/inline-api.ts#L195) and [DataviewApi.executeJs()](https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/api/plugin-api.ts#L452) in dataview seem to be just api functions as I can't find them referenced anywhere else in dataview plugin. I think it'll be ok to modify them as we like. 

executeJs doesn't have to call load() to trigger the execution. It can just call asyncEvalInContext so that it can return the value returned by asyncEvalInContext.

If it works, we'll be able to insert something like
```typescript
pages().limit(1)
```
in the dataview js source of a dbfolder.
And dbfolder plugin will effectively run the code 
```typescript
return DataviewService.getDataviewAPI().executeJs(`
pages().limit(1)
`)
```
to do the job.

What are your thoughts about plan A? Could you try it too?

**Comment by onoter** [comment]
@zcysxy @RafaelGB There's a workaround.
Make an object to receive the data returned by the `pages` api, and then return it. Like this: 
```typescript
let obj = new Obj();

DataviewService.getDataviewAPI().executeJs(`
obj.setPages(dv.pages().limit(1))
`)

return obj.getPages();
```
The definition of Obj is ommited. You get the idea.

**Comment by whatisaphone** [comment]
Maybe I missed something, but what about the using the `evaluate` method, which returns the results instead of rendering them?

https://github.com/blacksmithgu/obsidian-dataview/blob/bb594a27ba1eed130d7c2ab7eff0990578e93f62/src/api/inline-api.ts#L177

**Comment by onoter** [comment]
It's interesting how Github notification works. I get notified when not `@`ed; but not notified when `@`ed.

@whatisaphone Yeah, that context param of the `evaluate` function is a DataObject. The return type `Result<Literal, string>` is probably not what we want either. 

For anyone who's interested in using dataviewjs as the source, I found another way to do it.You can already use the `dataview` object in dbfolder's [Formula](https://rafaelgb.github.io/obsidian-db-folder/features/Formulas/): 
> dataview: expose the dataview API. (see [Dataview API](https://github.com/blacksmithgu/obsidian-dataview/blob/master/src/api/plugin-api.ts))

e.g. This code I found in this [video](https://www.youtube.com/watch?v=ym26gT798lQ&lc=UgzPE_Z9bfKMaKAeQKZ4AaABAg) by @DannyHatcher-Git :
```
${db.dataview.page(row.__file__.path).file.tasks.where(t=>!t.completed).length} Left
```

Here is the relevant code:
https://github.com/RafaelGB/obsidian-db-folder/blob/5388538a1f1b9b159c0728b4d7a6ad3e33a9da49/src/services/FormulaService.ts#L17-L25

I don't understand the code yet, but it would be easier than using eval function like what is done in the dataview plugin, as it's been done before. 

Still, I think the easiest way is to make a fr in dataview repo. I just made one [here](https://github.com/blacksmithgu/obsidian-dataview/issues/1967).

**Comment by whatisaphone** [comment]
You can always smuggle data in and out of `executeJs` using global builtins :slightly_smiling_face:  This works inside a `dataviewjs` block at least:

```js
WeakSet.__cursed_global__user_provided_query = `dv.pages('"/"')`;

dv.executeJs(`
    const result = ` + WeakSet.__cursed_global__user_provided_query + `
    WeakSet.__cursed_global__result = result;
`);

const result = WeakSet.__cursed_global__result;
dv.table(['File'], result.map((r) => [r.file.path]));

delete WeakSet.__cursed_global__user_provided_query;
delete WeakSet.__cursed_global__result;
```
