### ISSUE TITLE
[FR]: embed file content

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#633]
To show the entire content of the file asociated with the row without levlave the table

**Comment by RafaelGB** [comment]
![Image](https://user-images.githubusercontent.com/11924043/204287552-bf0f42d8-4ef9-4f4f-949f-2387e01039d0.png)

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/204637725-91d5ab7d-03a9-44d8-8a5a-5b000b1fb100.mov

tasks will be supported too!

**Comment by javiavid** [comment]
Sometimes there are metadata problems in notes and you need to open many individual notes to see where the problem is.

It would be very interesting to have an option in this feature to be able to choose what you want to show:
- Content of the note - As it is currently
- Metadata - Shows the YAML and inline metadata.
- Just Tasks

It would be nice if you could edit the metadata directly, but even without that it's a big step in troubleshooting.

**Comment by RafaelGB** [comment]
Could be interesting.
my proposed solution would be:
Keep default behavior under left click event

To aad a new group of options in the menu on the left click indicating those modes of opening
