### ISSUE TITLE
[Bug]: Changing or adding one frontmatter key-value pair reformats others

### ISSUE THREAD

**Issue by lguenth** [RafaelGB/obsidian-db-folder#729]
### What happened?

Hey!
I haven't really used DB Folder before and was just setting up a database when I found some undesired behaviour.

I realised that when I add a new key in the frontmatter or change the value of an existing one, the aliases would always get reformatted as well. Even if I didn't touch them myself nor added them as a column in the database.

For my literature notes, I usually use the citekey as the file name and add the actual title as an alias so I can still search for it easily. If I now change anything in the frontmatter through the database, the following happens:

https://user-images.githubusercontent.com/69049131/210759708-b89c079f-7df7-4cbf-9ad2-f530cd615203.mp4

Is there any way to stop the plugin from doing the formatting on fields which weren't changed?
(PS: Sorry if I missed a similar bug report!)

### What platform were you using?

Desktop

### Version of the plugin

3.2.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
hi 👋 

Its the way Obsidian understand the changes. Since 3.1.0 we are using the native API to edit the frontmatter information

https://github.com/RafaelGB/obsidian-db-folder/blob/09a774e292524d0852d2b592a7c7cdc010120ddb/src/services/EditEngineService.ts#L159

So there is nothing I can do. We can report this video to the Obsidian devs.

I have to say that the way of your aliases is persisted after the editions it is the correct one for a yaml list

**Comment by RafaelGB** [comment]
hi 👋,

I am not maintaining the csv stuff too much but we have plans for it this year with https://github.com/users/RafaelGB/projects/7/views/4?pane=issue&itemId=15181279


looks like your dates are migrated as timestamp millisecs (an standard for dates) I will check the reasons
