### ISSUE TITLE
[FR]: Formulas as Rollup

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#758]
### Contact Details

sarah.arminta@me.com

### Present your request

I have a Goals DB. I've been trying to figure out how to have a column which shows related Projects (files tagged #project where the goals:: field contains the current row and status:: = Active. 

How can I accomplish this? I've tried a formula column, but I can't even get the basic relation to work... I tried various forms of this: `${db.dataview.pages("#project").where(p => p.goals &&  p.goals.path.includes(row.__file__.name))}`

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Hello!

I was thinking about to include formulas as rollup option, so you can take advantage of the relation column ( it will substitute `db.dataview.pages("#project")` which is an expensive query and could affects the performnace) and manage your own behaviour (your `where()` or another js code)

This month I will be less active with the plugin due to labor issues, but I will continue uploading improvements thanks to your feedback!

**Comment by RafaelGB** [comment]
The new rollup formula expose the content of its pages


![Image](https://user-images.githubusercontent.com/11924043/212553203-de42c9cb-b3ca-48e4-be18-848443f6774f.png)

And you can manage the dataview record of every relation

```javascript
function relationsCheck(pages) {
    return pages.map(p => p.file.tags)
}

module.exports = relationsCheck
```

**Comment by arminta7** [comment]
Fantastic! That was fast!
