### ISSUE TITLE
[Bug]: have to click on the settings of the header of "Tag" format; otherwise, I can't create tags upon entering arbitrary strings

### ISSUE THREAD

**Issue by ghweili** [RafaelGB/obsidian-db-folder#850]
### What happened?

I'm using osbidian v.1.1.16; after creating a new vault and installing dataview and db-folder, I tried to create a database file based on a folder. This is possible, however, I can't enter arbitrary string in a column with a header of the "Tag" format, which shows "no options". However, if I click on the header to open its settings, then close this pane, then, when I enter an arbitrary string in a cell, the "create" option appears, as shown below.  

![image](https://user-images.githubusercontent.com/33361275/225059730-6438bd36-05d7-4b9d-9576-feae0c1ceaf6.png)
 

### What platform were you using?

Desktop

### Version of the plugin

3.3.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
I found the internal problem for this issue and will be fixed with the next version. It a question about default values. Since you create the column, the option of “editable” is mot created yet and is considered false by default. If you toggle twice the option at column settings it’s temporary fixed
