### ISSUE TITLE
[Bug]: Tags cannot be created from the column

### ISSUE THREAD

**Issue by TakoTsubo1995** [RafaelGB/obsidian-db-folder#854]
### Contact Details

crisrpa95@gmail.com

### What happened?

Hello since the update of DB folder i found a Bug that makes imposible create tags from the column like before i found aswell a solution but is not permanent.

Thank you for your work.

PD I post a hidden video of the solution https://www.youtube.com/watch?v=7HtIzOmGoRY

### What platform were you using?

Desktop

### Version of the plugin

3.3.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by ProStashio** [comment]
I do agree, this has been rather frustrating on my end. It's somewhat ruined the whole flow of why I use DB Folders to manage all my characters, settlements, groups, etc

**Comment by RafaelGB** [comment]
Sorry for the inconvenience, was fixed with this issue and will be added with the next minor version

https://github.com/RafaelGB/obsidian-db-folder/issues/850

**Comment by RafaelGB** [comment]
The problem was about the manual and formula source of the tags and selection types, a new column configuration is checked before the component of the cell is rendered but there is no configuration property until you change the option inside the column setttings.

So in case of it being empty the manual source will be used
