### ISSUE TITLE
[Bug]: Database not generated

### ISSUE THREAD

**Issue by ticmain** [RafaelGB/obsidian-db-folder#864]
### What happened?

I have created one database and it is functioning correctly.

However, I've tried creating additional databases and they do not generate database table. The configuration button appears in the correct spot and the markdown looks correct. But, when I open either of the new databases I create causes an error.

This error does not occur on the initial database I created. 

### What platform were you using?

Desktop

### Version of the plugin

3.3.2

### Relevant log output

```shell
Uncaught (in promise) TypeError: X.error is not a function
    at y2.eval (plugin:dbfolder:120:60233)
    at Generator.throw (<anonymous>)
    at s (plugin:dbfolder:1:799)
eval @ plugin:dbfolder:120
s @ plugin:dbfolder:1
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
It is a problem that we have been dragging on for a while.  It has to do with developer options.  Disable the logs in case the problem could be solved (dbfolder general options, last section).  For some reason it does not correctly find the error, info and warn options on some devices.  I'll keep investigating since I can't reproduce the bug

**Comment by ticmain** [comment]
I disabled the logs and the problem is resolved. 

Thank you!
