### ISSUE TITLE
[Bug]: Some way to lock column positions

### ISSUE THREAD

**Issue by aubreyz** [RafaelGB/obsidian-db-folder#901]
### What happened?

I have just started with DB Folder and can see I will find it useful. 

One thing is however bothering me a lot. If I filter by column (with that small magnifier at the left) there is no easy way (as far as I can see) to undo an individual column filter to no-filter apart from either deleting the text in the filter. There is not, unlike say excel a "all fields" in the dropdown (perhaps an issue in itself). However the inability to undo a column filter has a major side effect. 

The intuitive way to delete the text in a column filter is to drag over the text and press delete. However this drags the whole column so that the order of the columns changes. The only way seemingly to do it is to position the cursor at the end of the text and repeatedly press the backspace key. 

Summary: There are some usability issues here
a) There needs to be a "no filter" in the dropdown
b) There needs to be some way to lock the database to avoid key elements (column positions and what columns are shown from being altered, so that the user can just interact with the filtering aspects)

### What platform were you using?

Desktop

### Version of the plugin

3.4.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by aubreyz** [comment]
That's odd. This is a clear usability bug, and I spent time discussing it - i.e I cared . To have it just closed with no explanation at all makes me think twice about using this plugin....

**Comment by stefandanzl** [comment]
I personally did that without coordination with the plugin's owner in order to be able to focus on more critical issues as there currently still are a lot of them open (137 at the time of writing).
As described, usability is negativley affected but text can still be selected with double click or arrow keys.
I don't see the "select all or none" functionality fit in at the current UI configuration but it would indeed be a nice feature for faster workflows. 
Just as me you're of course free to solve the problem on your own and create a pull request

**Comment by RafaelGB** [comment]
Sorry for the inconvenience @aubreyz , the project is currently in what is called "technical bankruptcy" and @stefandanzl  is working hard to have a clear focus on the really important incidents.

For work reasons and because I maintain another plugin, the repository had been unchanged for some time.

**Comment by aubreyz** [comment]
> Sorry for the inconvenience @aubreyz , the project is currently in what is called "technical bankruptcy" and @stefandanzl is working hard to have a clear focus on the really important issues.
> For work reasons and because I maintain another plugin, the repository had been unchanged for some time.

I have no problem with that - nor is this the place for a meta-discussion about non-commercial software made with love. 
However, people do need to be able to decide what software to invest energies (either in assisting with development, bug reports or using at all). This means:
a) Not closing bugs (which this is - albeit I see a workaround above) as "Not planned". Perhaps some other sort of closure of deferral mechanism would be better. 
b) Having a clear statement of intent on the main page that this is software not in current development.
