### ISSUE TITLE
[FR] Insert tag in new note when source is tag

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#94]
**Is your feature request related to a problem? Please describe.**
If you have a tag source and create a new note by clicking on new. When updating the database it disappears.

**Describe the solution you'd like**
Add that tag in the note automatically.

**Comment by RafaelGB** [comment]
Good point right there!

**Comment by Mug521** [comment]
Is there an option to disable the auto creation of the tag inside the note in these scenarios?. Since I'm using templates to already assign the tag in the frontmatter when creating a new line in the database (and I'm using tags as a source of the database). So **the tag now appears twice** in these notes (once in the frontmatter--the one templater creates--and one as inline field created by the plugin).

Or may be is there an option for the plugin to put the tag in the frontmatter instead of inline?, that would make the work too for the ones who need the tag in the frontmatter.

And thanks a lot Rafael for creating such a masterpiece of plugin, I find it super useful.
